### ISSUE TITLE
Request for SBT_POST_TASKS

### ISSUE THREAD

**Issue by T-PWK** [heroku/heroku-buildpack-scala#113]
It would be extremely handy if this build pack had **SBT_POST_TASKS**, implemented in a very similar way as `SBT_PRE_TASKS`

That task could be used to perform some cleanup operations.

One of the challenges is that a Play project with multiple modules will exceed the slug size limits very quickly. Unfortunately guideline to reduce slug size via overriding stage task (as proposed [here](https://devcenter.heroku.com/articles/reducing-the-slug-size-of-play-2-x-applications#using-sbt-to-clean-build-artifacts)) do not work.

Also, having in mind that SBT is quite dynamically changing tool, having a solution nearly independent of SBT version would be ideal.

**Comment by jkutner** [comment]
Yea, this is a reasonable request. SBT is not as malleable as I would like, especially with Play in play.

I'm trying to move away from env vars to configure the buildpack, so instead of `SBT_POST_TASKS`, I might support an `sbt.post-tasks` property in the `system.properties` file (we already support `sbt.pre-tasks`).

Would that work for you?

**Comment by T-PWK** [comment]
Hi,

Yes, that approach would be ideal. Thanks.

**Comment by jkutner** [comment]
The buildpack now supports custom `SBT_TASKS` which overrides all task that are run; superseding this request. For example:

```
$ heroku config:set SBT_TASKS="clean build prune"
```
